"""
Facade licence — centralise l'accès au module sca.license_check (injecté par build).

Si le module est absent (mode script source), toutes les fonctions retournent
les valeurs enterprise par défaut (aucune restriction).

Usage dans le code SCA :
    from sca.license_facade import get_tier, has_feature, tier_at_least
"""
import logging

logger = logging.getLogger("sca.license_facade")

# Tier hierarchy for ordinal comparisons
# solo_plus/team_plus: same ordinal as solo/team (upsell on number of machines
# on the admin.codefixture.com side, no extra features/scan capacity
# except team_plus, whose file quota is higher, cf. TIER_LIMITS).
TIER_ORDER = {"demo": 0, "solo": 1, "solo_plus": 1, "team": 2, "team_plus": 2, "enterprise": 3}


def _binary_mode() -> bool:
    """Return True only when running inside the distributed binary."""
    import sys
    lc = sys.modules.get("sca.license_check")
    if lc is None:
        try:
            import sca.license_check as lc  # type: ignore[no-redef]
        except ImportError:
            return False
    return not getattr(lc, "_IS_SOURCE_MODE", True)

# Enterprise defaults (source mode = no restriction)
_DEFAULTS = {
    "tier": "enterprise",
    "features": [
        "taint", "multifile", "compliance", "cross_file",
        "sarif", "sbom",
    ],
    "max_files": 0,       # 0 = unlimited
    "max_loc": 0,         # 0 = unlimited (Source Lines Of Code)
    "exports": ["json", "html", "sarif", "sbom"],
    "seats": 0,           # 0 = unlimited
    "max_custom_rules": 999999,
    "allowed_categories": [
        "SECURITY", "ARCH", "UI", "UX", "MAINTENANCE",
        "DEPENDENCIES", "CICD", "DATABASE",
    ],
    "org_id": "",  # source mode = no license, hence no org_id
}


def get_tier() -> str:
    """Return the current license tier (demo, solo, team, enterprise)."""
    if not _binary_mode():
        return _DEFAULTS["tier"]
    try:
        from sca.license_check import get_tier as _get_tier
        return _get_tier()
    except (ImportError, AttributeError):
        return _DEFAULTS["tier"]


def get_features() -> list:
    """Return the active features for the current license."""
    if not _binary_mode():
        return list(_DEFAULTS["features"])
    try:
        from sca.license_check import get_features as _get_features
        return _get_features()
    except (ImportError, AttributeError):
        return list(_DEFAULTS["features"])


def get_max_files() -> int:
    """Return the file count limit for the license (0 = unlimited)."""
    if not _binary_mode():
        return _DEFAULTS["max_files"]
    try:
        from sca.license_check import get_max_files as _get_max_files
        return _get_max_files()
    except (ImportError, AttributeError):
        return _DEFAULTS["max_files"]


def get_max_loc() -> int:
    """Return the SLOC (source lines of code) limit (0 = unlimited).

    Combined restrictively with max_files: whichever limit is hit first
    stops the scan.
    """
    if not _binary_mode():
        return _DEFAULTS["max_loc"]
    try:
        from sca.license_check import get_max_loc as _get_max_loc
        return _get_max_loc()
    except (ImportError, AttributeError):
        return _DEFAULTS["max_loc"]


def get_exports() -> list:
    """Return the list of allowed export formats."""
    if not _binary_mode():
        return list(_DEFAULTS["exports"])
    try:
        from sca.license_check import get_exports as _get_exports
        return _get_exports()
    except (ImportError, AttributeError):
        return list(_DEFAULTS["exports"])


def get_seats() -> int:
    """Return the number of allowed seats (0 = unlimited)."""
    if not _binary_mode():
        return _DEFAULTS["seats"]
    try:
        from sca.license_check import get_seats as _get_seats
        return _get_seats()
    except (ImportError, AttributeError):
        return _DEFAULTS["seats"]


def get_max_custom_rules() -> int:
    """Return the custom rules limit (999999 = unlimited)."""
    if not _binary_mode():
        return _DEFAULTS["max_custom_rules"]
    try:
        from sca.license_check import get_max_custom_rules as _get
        return _get()
    except (ImportError, AttributeError):
        return _DEFAULTS["max_custom_rules"]


def get_allowed_categories() -> list:
    """Return the SCA categories allowed for the current license."""
    if not _binary_mode():
        return list(_DEFAULTS["allowed_categories"])
    try:
        from sca.license_check import get_allowed_categories as _get
        return _get()
    except (ImportError, AttributeError):
        return list(_DEFAULTS["allowed_categories"])


def get_org_id() -> str:
    """Return the org_id (stable customer identifier) of the current license.

    Used to link rules generated by the rule-generation extension to the license that produced
    them (see its internal design docs C9). Empty string if there is no
    valid license or the field is unset.
    """
    if not _binary_mode():
        return _DEFAULTS["org_id"]
    try:
        from sca.license_check import get_org_id as _get_org_id
        return _get_org_id()
    except (ImportError, AttributeError):
        return _DEFAULTS["org_id"]


def has_feature(feature: str) -> bool:
    """Check whether a feature is available in the current license."""
    return feature in get_features()


def tier_at_least(min_tier: str) -> bool:
    """Check whether the current tier is >= min_tier in the hierarchy."""
    current = TIER_ORDER.get(get_tier(), 0)
    required = TIER_ORDER.get(min_tier, 0)
    return current >= required


def get_license_info() -> dict:
    """Return a full dict of the current license's information."""
    return {
        "tier": get_tier(),
        "features": get_features(),
        "max_files": get_max_files(),
        "max_loc": get_max_loc(),
        "exports": get_exports(),
        "seats": get_seats(),
        "max_custom_rules": get_max_custom_rules(),
        "allowed_categories": get_allowed_categories(),
        "org_id": get_org_id(),
    }
