"""
Publisher signature verification (Ed25519) — public key only.

Reused for TWO distinct verifications that share the SAME publisher key
pair (cf. its internal design docs step 3,
CONSTRAINTS.md C9):

  1. Signature of the ``.sca`` rules generated by the rule-generation extension, verified when
     loading a custom rule (cf. sca/rule_loader.py::
     _verify_external_provenance).
  2. Signature of the ``manifest.json`` of the external module
     itself, verified before its dynamic import (cf. the (excluded) external-module loader::
     load_external_module).

SCA never signs anything itself: only the PRIVATE key (held by
admin.codefixture.com) signs. This module contains and needs only the
PUBLIC key — consistent with CONSTRAINTS.md C9 ("SCA remains the final
decision-maker, the rule-generation extension only produces the protected content").

Why Ed25519 rather than the HMAC already used for license.key
(sca/license_check.py): HMAC is symmetric — the same secret signs and
verifies. Embedding it in the client binary would let anyone who extracts
it forge fake rule or manifest signatures, which would defeat the purpose
of C9. Ed25519 is asymmetric: only the public key travels in the client
binary, the private key never leaves the publisher.
"""
from __future__ import annotations

import base64
import binascii
import hashlib
import json
import logging

logger = logging.getLogger("sca.sign")

# Publisher public key (Ed25519, 32 bytes, hex-encoded) — replaced by
# the build script (AuditDistrib) before packaging, exactly like
# _SECRET in sca/license_check.py. Empty in source mode: no
# verification can ever succeed until the build has injected the
# real key (deny by default, no permissive fallback).
_EDITOR_PUBLIC_KEY_HEX: str = ""


def _decode_signature(signature: str) -> bytes | None:
    """Decode a ``base64:<...>`` (or raw base64) signature value.

    Returns None on invalid encoding — never raises, so the caller never
    has to catch an exception from this helper.
    """
    if not signature:
        return None
    value = signature[len("base64:"):] if signature.startswith("base64:") else signature
    try:
        return base64.b64decode(value, validate=True)
    except (binascii.Error, ValueError):
        return None


def verify_ed25519(message: bytes, signature: str, public_key_hex: str | None = None) -> bool:
    """Verify an Ed25519 signature over ``message``.

    Always returns a boolean (never raises) — the caller must treat
    ``False`` as an explicit rejection of the rule/module, never as
    "possibly valid".
    """
    key_hex = public_key_hex if public_key_hex is not None else _EDITOR_PUBLIC_KEY_HEX
    if not key_hex:
        logger.debug("[sign] Aucune clé publique éditeur configurée — vérification refusée par défaut")
        return False

    signature_bytes = _decode_signature(signature)
    if signature_bytes is None:
        logger.debug("[sign] Signature illisible (encodage invalide ou absente)")
        return False

    try:
        key_bytes = bytes.fromhex(key_hex)
    except ValueError:
        logger.error("[sign] Clé publique éditeur mal formée (hex invalide)")
        return False

    try:
        from cryptography.exceptions import InvalidSignature
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
    except ImportError:
        logger.error("[sign] Bibliothèque 'cryptography' indisponible — vérification de signature impossible")
        return False

    try:
        public_key = Ed25519PublicKey.from_public_bytes(key_bytes)
        public_key.verify(signature_bytes, message)
        return True
    except InvalidSignature:
        return False
    except (ValueError, TypeError) as exc:
        logger.debug("[sign] Erreur de vérification : %s", exc)
        return False


def compute_rule_content_hash(sca_source: str) -> bytes:
    """Compute the canonical signed content hash for an the rule-generation extension ``.sca`` rule.

    Contract (see its internal design docs §7.1): sha256 of the full
    ``.sca`` source text, EXCLUDING the ``signature`` line of the metadata
    block (the field carrying the signature cannot be part of the signed
    message). Any line whose first word is ``signature`` is stripped before
    hashing — this convention must be mirrored exactly on the generator
    side (the rule-generation extension).

    Assumes a ``.sca`` file generated by the rule-generation extension carries exactly one rule,
    so the hash covers the entire file.
    """
    kept_lines = [
        line for line in sca_source.splitlines()
        if line.strip().split(None, 1)[:1] != ["signature"]
    ]
    canonical = "\n".join(kept_lines).encode("utf-8")
    return hashlib.sha256(canonical).digest()


def compute_manifest_content_hash(manifest: dict) -> bytes:
    """Compute the canonical signed content hash for an the rule-generation extension ``manifest.json``.

    sha256 of the canonical JSON serialization (sorted keys, compact
    separators) of the manifest, EXCLUDING the ``signature`` field itself.
    Reuses the same editor key pair as :func:`compute_rule_content_hash`.
    """
    payload = {k: v for k, v in manifest.items() if k != "signature"}
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
    return hashlib.sha256(canonical).digest()
