"""
AST nodes for the .sca DSL.

Represents the intermediate structure between parsing a .sca file
and compiling it to the JSON format consumed by rule_loader.py.
"""
from dataclasses import dataclass, field
from typing import Dict, List


@dataclass
class MatchRegexBlock:
    """A match block — a pattern (regex or plain text) with scope and conditions.

    If is_text=True, the pattern is plain text that gets auto-escaped
    during compilation (`*` is converted to `.*`).
    """

    pattern: str = ""
    is_text: bool = False
    scope: str = "line"
    with_pattern: str = ""
    with_is_text: bool = False
    pattern_not: str = ""
    pattern_not_is_text: bool = False
    pattern_inside: str = ""
    pattern_not_inside: str = ""
    line_number: int = 0


@dataclass
class MatchAstBlock:
    """A match ast block — a tree-sitter S-expression pattern."""

    pattern: str = ""
    line_number: int = 0


@dataclass
class MatchFileContainsBlock:
    """A match file_contains block — presence/absence of patterns in a file."""

    has_patterns: List[str] = field(default_factory=list)
    not_has_patterns: List[str] = field(default_factory=list)
    scope: str = "file"
    line_number: int = 0


@dataclass
class SourceSpec:
    """Specification of a taint source (untrusted input)."""

    pattern: str = ""
    kind: str = "http"
    line_number: int = 0


@dataclass
class SinkSpec:
    """Specification of a taint sink (dangerous function)."""

    pattern: str = ""
    arg_index: int = 0
    line_number: int = 0


@dataclass
class SanitizerSpec:
    """Specification of a taint sanitizer (cleansing function)."""

    pattern: str = ""
    line_number: int = 0


@dataclass
class PassthroughSpec:
    """Specification of a taint passthrough (transformation that preserves taint)."""

    pattern: str = ""
    line_number: int = 0


@dataclass
class I18nBlock:
    """A block of internationalized text (en, fr, es, de)."""

    texts: Dict[str, str] = field(default_factory=dict)
    line_number: int = 0


@dataclass
class MetadataBlock:
    """Compliance metadata block (CWE, OWASP, ISO 27001) and provenance
    fields for rules generated by the rule-generation extension (see CONSTRAINTS.md C9,
    its internal design docs §7.1).

    The six provenance fields (generated_by, generated_at,
    generator_version, manifest_hash, org_id, signature) stay empty for
    any builtin or manually written custom rule — their presence
    triggers signature verification at load time
    (sca/rule_loader.py::_verify_external_provenance).
    """

    cwe: List[str] = field(default_factory=list)
    cve: List[str] = field(default_factory=list)
    owasp: str = ""
    iso27001: List[str] = field(default_factory=list)
    wcag: List[str] = field(default_factory=list)
    asvs: List[str] = field(default_factory=list)
    generated_by: str = ""
    generated_at: str = ""
    generator_version: str = ""
    manifest_hash: str = ""
    org_id: str = ""
    signature: str = ""
    line_number: int = 0


@dataclass
class LicenseBlock:
    """License requirement block (tier, features)."""

    min_tier: str = "demo"
    features: List[str] = field(default_factory=list)
    demo_fallback: bool = False
    line_number: int = 0


# Alias for backward compat (old name)
RequiresBlock = LicenseBlock


@dataclass
class FileConditionBlock:
    """A requires block — file conditions (has/not_has/min_lines/path_contains).

    Used to filter files before patterns are applied.
    If combined with a match, the finding is reported at the pattern's line.
    If standalone (no match), the finding is file-level (line 1).
    """

    has_patterns: List[str] = field(default_factory=list)
    not_has_patterns: List[str] = field(default_factory=list)
    path_contains: List[str] = field(default_factory=list)
    not_path_has_file: List[str] = field(default_factory=list)
    min_lines: int = 0
    scope: str = "file"
    line_number: int = 0


@dataclass
class RuleNode:
    """Root node representing one complete .sca rule."""

    id: str = ""
    language: str = ""
    category: str = ""
    severity: str = ""
    confidence: int = 80
    mode: str = ""  # optional — inferred if absent
    match_blocks: List = field(default_factory=list)
    file_conditions: List[FileConditionBlock] = field(default_factory=list)
    sources: List[SourceSpec] = field(default_factory=list)
    sinks: List[SinkSpec] = field(default_factory=list)
    sanitizers: List[SanitizerSpec] = field(default_factory=list)
    passthroughs: List[PassthroughSpec] = field(default_factory=list)
    message: I18nBlock = field(default_factory=I18nBlock)
    risk: I18nBlock = field(default_factory=I18nBlock)
    solution: I18nBlock = field(default_factory=I18nBlock)
    benefit: I18nBlock = field(default_factory=I18nBlock)
    metadata: MetadataBlock = field(default_factory=MetadataBlock)
    license: LicenseBlock = field(default_factory=LicenseBlock)
    fix_before: str = ""
    fix_after: str = ""
    hook: str = ""
    line_number: int = 0
